version: '2'
services:
  RT-Database:
    scale: 1
    start_on_create: true
  RT4:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  MessageQueue:
    retain_ip: true
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 5672
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  Fetchmail:
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 9090
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
